# Copyright (c) 2024 Daniel Seichter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import os
import subprocess
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
ICONS_DIR = ROOT / "icons"
SRC_DIR = ROOT / "src"
QRC_PATH = SRC_DIR / "resources.qrc"
RESOURCE_MODULE_PATH = SRC_DIR / "resources_rc.py"
ICONS_PY_PATH = SRC_DIR / "icons.py"


def collect_icons() -> list[str]:
    """Collect all PNG icon filenames from the icons directory."""
    return sorted([path.name for path in ICONS_DIR.glob("*.png")])


def generate_qrc(icon_files: list[str]) -> None:
    """Generate src/resources.qrc from the available PNG icons."""
    lines = [
        "<!DOCTYPE RCC>",
        "<RCC version=\"1.0\">",
        "  <qresource prefix=\"/icons\">",
    ]

    for icon_file in icon_files:
        lines.append(f"    <file alias=\"{icon_file}\">../icons/{icon_file}</file>")

    lines.extend([
        "  </qresource>",
        "</RCC>",
        "",
    ])

    QRC_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"✓ Generated {QRC_PATH}")


def compile_qrc() -> None:
    """Compile src/resources.qrc to src/resources_rc.py."""
    commands = [
        ["pyside6-rcc", str(QRC_PATH), "-o", str(RESOURCE_MODULE_PATH)],
        ["pyrcc6", str(QRC_PATH), "-o", str(RESOURCE_MODULE_PATH)],
    ]

    for command in commands:
        try:
            subprocess.run(command, check=True, capture_output=True, text=True)
            print(f"✓ Compiled Qt resources via {command[0]}")
            return
        except (FileNotFoundError, subprocess.CalledProcessError):
            continue

    raise RuntimeError("Could not compile resources.qrc. Install PySide6 tools (pyside6-rcc/pyrcc6).")


def generate_icons_py(icon_files: list[str]) -> None:
    """Generate src/icons.py with Qt resource path mapping."""
    lines = [
        "#----------------------------------------------------------------------",
        "# This file was generated by generate_icon.py",
        "# It loads icons from Qt resources (resources.qrc -> resources_rc.py)",
        "#",
        "",
        "from PySide6.QtGui import QIcon",
        "",
        "try:",
        "    import resources_rc  # noqa: F401",
        "except ImportError:",
        "    try:",
        "        from . import resources_rc  # type: ignore # noqa: F401",
        "    except ImportError:",
        "        resources_rc = None",
        "",
        "",
        "ICON_PATHS = {",
    ]

    for icon_file in icon_files:
        icon_key = icon_file[:-4].lower()
        lines.append(f"    '{icon_key}': ':/icons/{icon_file}',")

    lines.extend([
        "}",
        "",
        "",
        "def get_icon(name: str) -> QIcon:",
        "    \"\"\"Get QIcon by name from Qt resources.\"\"\"",
        "    resource_path = ICON_PATHS.get(name.lower())",
        "    if resource_path is None:",
        "        print(f\"Warning: Icon '{name}' not found in catalog\")",
        "        return QIcon()",
        "    return QIcon(resource_path)",
        "",
    ])

    ICONS_PY_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"✓ Generated {ICONS_PY_PATH}")


def generate_ico() -> None:
    """Generate workdir.ico from the main logo PNG."""
    logo_file = ICONS_DIR / "folder_open_48dp_8B1A10_FILL0_wght400_GRAD0_opsz48.png"
    ico_path = ICONS_DIR / "workdir.ico"

    if logo_file.exists():
        with Image.open(logo_file) as img:
            img.save(
                ico_path,
                format="ICO",
                sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
            )
            print(f"✓ Generated {ico_path}")
    else:
        print(f"Warning: {logo_file} not found, skipping ICO generation")


if __name__ == "__main__":
    print("Generating Qt-resource icon files...\n")
    icons = collect_icons()
    generate_qrc(icons)
    compile_qrc()
    generate_icons_py(icons)
    generate_ico()
    print("\nDone!")
