#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It loads icons from Qt resources (resources.qrc -> resources_rc.py)
#

from PySide6.QtGui import QIcon

try:
    import resources_rc  # noqa: F401
except ImportError:
    try:
        from . import resources_rc  # type: ignore # noqa: F401
    except ImportError:
        resources_rc = None


ICON_PATHS = {
    'folder_open_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/folder_open_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
    'folder_open_48dp_8b1a10_fill0_wght400_grad0_opsz48': ':/icons/folder_open_48dp_8B1A10_FILL0_wght400_GRAD0_opsz48.png',
    'globe_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/globe_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
    'info_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/info_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
    'logout_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/logout_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
    'settings_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/settings_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
    'update_24dp_8b1a10_fill0_wght400_grad0_opsz24': ':/icons/update_24dp_8B1A10_FILL0_wght400_GRAD0_opsz24.png',
}


def get_icon(name: str) -> QIcon:
    """Get QIcon by name from Qt resources."""
    resource_path = ICON_PATHS.get(name.lower())
    if resource_path is None:
        print(f"Warning: Icon '{name}' not found in catalog")
        return QIcon()
    return QIcon(resource_path)
